stages:
  - prebuild
  - build
  - release
  - deploy
  - clear
variables:
    CONF_DIR: /opt/servicios/$CI_PROJECT_NAME
Configurar servidor para despliegue de la aplicación (development):
  stage: prebuild
  tags:
    - runner-development
  script:
    - sudo rm -rf $CONF_DIR/ansible && sudo cp ./ansible -R $CONF_DIR/ansible
    - ansible-playbook $CONF_DIR/ansible/0_prebuilding.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) configPath=$CONF_DIR"
  only:
    - development

Construir la aplicación con la configuración del ambiente (development):
  stage: build
  tags:
    - runner-development
  script:
    - ansible-playbook $CONF_DIR/ansible/1_install.yaml  --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd)"
  only:
    - development
  cache:
    paths:
      - ./node_modules/

Generar Release de la aplicación (development):
  stage: release
  tags:
    - runner-development
  script:
    - ansible-playbook $CONF_DIR/ansible/3_releasing.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) configPath=$CONF_DIR projectCommitSha=$CI_COMMIT_SHORT_SHA"
  only:
    - development
  cache:
    paths:
      - ./node_modules/

Desplegar la aplicación (development):
  stage: deploy
  tags:
    - runner-development
  script:
    - sudo ansible-playbook  $CONF_DIR/ansible/4_deploying.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) projectCommitSha=$CI_COMMIT_SHORT_SHA configPath=$CONF_DIR"
  only:
    - development

Limpiar (development):
  stage: clear
  tags:
    - runner-development
  script:
    - sudo rm -rf /home/gitlab-runner/cache && sudo rm -rf /home/gitlab-runner/builds && sudo rm -rf $CONF_DIR/ansible && sudo rm -rf $CONF_DIR/builds && sudo rm -rf /opt/clientes_iop/$CI_PROJECT_NAME/ansible
  only:
    - development


Configurar servidor para despliegue de la aplicación (test):
  stage: prebuild
  tags:
    - runner-test
  script:
    - sudo rm -rf $CONF_DIR/ansible && sudo cp ./ansible -R $CONF_DIR/ansible
    - ansible-playbook $CONF_DIR/ansible/0_prebuilding.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) configPath=$CONF_DIR"
  only:
    - test

Construir la aplicación con la configuración del ambiente (test):
  stage: build
  tags:
    - runner-test
  script:
    - ansible-playbook $CONF_DIR/ansible/1_install.yaml  --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd)"
  only:
    - test
  cache:
    paths:
      - ./node_modules/

Generar Release de la aplicación (test):
  stage: release
  tags:
    - runner-test
  script:
    - ansible-playbook $CONF_DIR/ansible/3_releasing.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) configPath=$CONF_DIR projectCommitSha=$CI_COMMIT_SHORT_SHA"
  only:
    - test
  cache:
    paths:
      - ./node_modules/

Desplegar la aplicación (test):
  stage: deploy
  tags:
    - runner-test
  script:
    - sudo ansible-playbook  $CONF_DIR/ansible/4_deploying.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) projectCommitSha=$CI_COMMIT_SHORT_SHA configPath=$CONF_DIR"
  only:
    - test

Limpiar (test):
  stage: clear
  tags:
    - runner-test
  script:
    - sudo rm -rf /home/gitlab-runner/cache && sudo rm -rf /home/gitlab-runner/builds && sudo rm -rf $CONF_DIR/ansible && sudo rm -rf $CONF_DIR/builds && sudo rm -rf /opt/clientes_iop/$CI_PROJECT_NAME/ansible
  only:
    - test


Configurar servidor para despliegue de la aplicación (master):
  stage: prebuild
  tags:
    - runner-master
  script:
    - sudo rm -rf $CONF_DIR/ansible && sudo cp ./ansible -R $CONF_DIR/ansible
    - ansible-playbook $CONF_DIR/ansible/0_prebuilding.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) configPath=$CONF_DIR"
  only:
    - master

Construir la aplicación con la configuración del ambiente (master):
  stage: build
  tags:
    - runner-master
  script:
    - ansible-playbook $CONF_DIR/ansible/1_install.yaml  --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd)"
  only:
    - master
  cache:
    paths:
      - ./node_modules/

Generar Release de la aplicación (master):
  stage: release
  tags:
    - runner-master
  script:
    - ansible-playbook $CONF_DIR/ansible/3_releasing.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) configPath=$CONF_DIR projectCommitSha=$CI_COMMIT_SHORT_SHA"
  only:
    - master
  cache:
    paths:
      - ./node_modules/

Desplegar la aplicación (master):
  stage: deploy
  tags:
    - runner-master
  script:
    - sudo ansible-playbook  $CONF_DIR/ansible/4_deploying.yaml --extra-vars="projectName=$CI_PROJECT_NAME projectPath=$(pwd) projectCommitSha=$CI_COMMIT_SHORT_SHA configPath=$CONF_DIR"
  only:
    - master

Limpiar (master):
  stage: clear
  tags:
    - runner-master
  script:
    - sudo rm -rf /home/gitlab-runner/cache && sudo rm -rf /home/gitlab-runner/builds && sudo rm -rf $CONF_DIR/ansible && sudo rm -rf $CONF_DIR/builds && sudo rm -rf /opt/clientes_iop/$CI_PROJECT_NAME/ansible
  only:
    - master