--- # instalar paquetes necesarios
- name: Instalar paquetes básicos necesarios
  apt:
    name: [curl, wget, apt-transport-https, dirmngr, gnupg, ca-certificates]
    state: present

- name: Instalar build-essential
  apt:
    name: build-essential
    state: present

- name: Registrar el directorio de artefactos
  stat:
    path: '{{ configPath }}/builds'
  register: artifactsDir

- name: Crear el directorio de artefactos
  file:
    path: '{{ configPath }}/builds'
    owner: gitlab-runner
    group: gitlab-runner
    state: directory
    mode: 0755
  when: artifactsDir.stat.isdir is not defined

